// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuartzTask.db;

#nullable disable

namespace QuartzTask.Migrations.DailyTask
{
    [DbContext(typeof(DailyTaskContext))]
    [Migration("20231016050313_dailyTask_db_init")]
    partial class dailyTask_db_init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuartzTask.Domain.Entities.DayDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DaySummaryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("LastModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoundId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DaySummaryId");

                    b.ToTable("DayDetails", (string)null);
                });

            modelBuilder.Entity("QuartzTask.Domain.Entities.DaySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DateSummary")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("int");

                    b.Property<int>("TotalTasks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DaySummary");
                });

            modelBuilder.Entity("QuartzTask.Domain.Entities.DayDetails", b =>
                {
                    b.HasOne("QuartzTask.Domain.Entities.DaySummary", "DaySummary")
                        .WithMany("DayDetails")
                        .HasForeignKey("DaySummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaySummary");
                });

            modelBuilder.Entity("QuartzTask.Domain.Entities.DaySummary", b =>
                {
                    b.Navigation("DayDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
