// <auto-generated />
using System;
using JobTaskInpress.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobTaskInpress.Api.Migrations.DailyTask
{
    [DbContext(typeof(DailyTaskContext))]
    [Migration("20231010104306_task_context_migratiob")]
    partial class task_context_migratiob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobTaskInpress.Domain.Entities.DayDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DaySummaryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("LastModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoundId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DaySummaryId");

                    b.ToTable("DayDetails", (string)null);
                });

            modelBuilder.Entity("JobTaskInpress.Domain.Entities.DaySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateSummary")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("int");

                    b.Property<int>("TotalTasks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DaySummary");
                });

            modelBuilder.Entity("JobTaskInpress.Domain.Entities.DayDetails", b =>
                {
                    b.HasOne("JobTaskInpress.Domain.Entities.DaySummary", "DaySummary")
                        .WithMany("DayDetails")
                        .HasForeignKey("DaySummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaySummary");
                });

            modelBuilder.Entity("JobTaskInpress.Domain.Entities.DaySummary", b =>
                {
                    b.Navigation("DayDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
